language: node_js
node_js:
  - 6
script:
  - node --version
  - yarn --version
  - yarn run test
before_deploy:
  - yarn run build
deploy:
  provider: surge
  project: ./build/
  domain: http://deserted-belief.surge.sh/
notifications:
  email:
    on_failure: change
cache: yarn
